services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: shroom
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
  redis:
    image: redis
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data
  grobid:
    image: lfoppiano/grobid:latest-crf
    ulimits:
      core: 0
    ports:
      - 8070:8070
volumes:
  postgres-data:
  redis-data: