apo: 'druid:hv992ry2431'
default_collection: ~

grobid:
  host: 'http://localhost:8070'
  # True to lookup additional metadata by DOI
  consolidate: true

sdr_api:
  url: http://localhost:3006
  email: shroom@dlss.sul.stanford.edu

dor_services:
  url: "http://localhost:3003"

workflow:
  url: "http://localhost:3001"

purl:
  url: "https://sul-purl-stage.stanford.edu"

redis:
  url: redis://localhost:6379/

# Use classname of the metadata extraction service.
metadata_extraction_service: Grobid
# metadata_extraction_service: Gemini
