apo: 'druid:hv992ry2431'

grobid:
  host: 'http://localhost:8070'

sdr_api:
  url: http://localhost:3006
  email: shroom@dlss.sul.stanford.edu

dor_services:
  url: "http://localhost:3003"

workflow:
  url: "http://localhost:3001"

purl:
  url: "https://sul-purl-stage.stanford.edu"
