apo: 'druid:zx485kb6348'

grobid:
  host: 'http://localhost:8070'

file_store:
  path: 'tmp/files'

sdr_api:
  url: http://sdr-api:3006
  email: shroom@dlss.sul.stanford.edu
  password: notusedanywhere