sdr_api:
  url: https://sdr-api-qa.stanford.edu

dor_services:
  url: https://dor-services-qa-lb.stanford.edu

default_collection: druid:nk652wp5367

features_enabled:
  ror: false
  clean_geonames: false
