# frozen_string_literal: true

module Works
  # Renders the raw TEI and Bibtex generated by Grobid
  class GrobidServiceInfoComponent < ViewComponent::Base
    def initialize(grobid_service:)
      @grobid_service = grobid_service
      super()
    end

    attr_reader :grobid_service

    delegate :tei, :bibtex, to: :grobid_service

    def render?
      grobid_service.present?
    end
  end
end
